int lane_detection_crop_floor = 0;
int lane_detection_crop_roof = 250;
int lane_detection_crop_x_start = 200;
int lane_detection_crop_x_stop = 1100;
int lane_detection_crop_x_horizon = 550;

uint8_t lane_detection_blur_level = 3;

short lane_detection_canny_thresh_low = 50;
short lane_detection_canny_thresh_high = 150;

int lane_perspective_floor = 250;
int lane_perspective_roof = 750;
int lane_perspective_startfloor = 250;
int lane_perspective_stopfloor = 750;
int lane_perspective_startroof = 250;
int lane_perspective_stoproof = 750;

int lane_threshold = 150;

int lane_left_rect_x = 0;
int lane_left_rect_y = 300;
int lane_left_rect_width = 30;
int lane_left_rect_height = 40;

int lane_right_rect_x = 200;
int lane_right_rect_y = 300;
int lane_right_rect_width = 30;
int lane_right_rect_height = 40;
